spring:
  servlet:
    multipart:
      enabled: true
      file-size-threshold: 2MB
      max-file-size: 20MB
      max-request-size: 50MB

cloud:
  aws:
    credentials:
      profile-name: darkrose
    region:
      static: us-east-1
    stack:
      auto: false

appconfig:      
  bucket:
    name: awstg-s3-fileupload


